export const ApiConstants = {
  API_GET_ALL_PRODUCTS: "API_GET_ALL_PRODUCTS",
  API_GET_ALL_PRODUCTS_SUCCESS: "API_GET_ALL_PRODUCTS_SUCCESS",
  API_GET_JEWELERY: "API_GET_JEWELERY",
  API_GET_JEWELERY_SUCCESS: "API_GET_JEWELERY_SUCCESS",
  API_USER_LOGIN_LOAD: "API_USER_LOGIN_LOAD",
  API_USER_LOGIN_LOAD_SUCCESS: "API_USER_LOGIN_LOAD_SUCCESS",
};
